from enum import StrEnum


class UserRole(StrEnum):
    USER = "USER"
    AGENT = "AGENT"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


class UserType(StrEnum):
    CUSTOMER = "CUSTOMER"
    ADVERTISING_AGENT = "ADVERTISING_AGENT"
    BUSINESS_AGENT = "BUSINESS_AGENT"
    ARTISAN = "ARTISAN"
    ADVERTISING = "ADVERTISING"
    PROPERTY_DEVELOPMENT = "PROPERTY_DEVELOPMENT"
    SURVEYOR = "SURVEYOR"
    ARCHITECT = "ARCHITECT"
    LEGAL_DRAFTS_MAN = "LEGAL_DRAFTS_MAN"
    LANDLORD = "LANDLORD"


class OperatingMode(StrEnum):
    STANDALONE = "STANDALONE"
    NOXER_MANAGED = "NOXER_MANAGED"


class SubscriptionStatus(StrEnum):
    INACTIVE = "INACTIVE"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AgentStatus(StrEnum):
    PENDING = "PENDING"
    PAID = "PAID"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISABLED = "DISABLED"


class DocumentType(StrEnum):
    NIN = "NIN"
    CAC = "CAC"
    SCUM = "SCUM"


class DocumentStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class VisibleContactType(StrEnum):
    AGENT = "AGENT"
    NOXER = "NOXER"


class AdminAction(StrEnum):
    AGENT_APPROVED = "AGENT_APPROVED"
    AGENT_REJECTED = "AGENT_REJECTED"
    AGENT_DISABLED = "AGENT_DISABLED"
    AGENT_ENABLED = "AGENT_ENABLED"
    AGENT_PROFILE_CREATED = "AGENT_PROFILE_CREATED"
    ADMIN_CREATED = "ADMIN_CREATED"
    ADMIN_UPDATED = "ADMIN_UPDATED"
    ADMIN_DISABLED = "ADMIN_DISABLED"
    ADMIN_ENABLED = "ADMIN_ENABLED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_APPROVED = "DOCUMENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    PROPERTY_CREATED = "PROPERTY_CREATED"
    PROPERTY_UPDATED = "PROPERTY_UPDATED"
    PROPERTY_DELETED = "PROPERTY_DELETED"
    PROPERTY_MEDIA_UPLOADED = "PROPERTY_MEDIA_UPLOADED"
    PROPERTY_MEDIA_DELETED = "PROPERTY_MEDIA_DELETED"
    PROPERTY_HIDDEN = "PROPERTY_HIDDEN"
    PROPERTY_RESTORED = "PROPERTY_RESTORED"
    PROPERTY_ADMIN_DELETED = "PROPERTY_ADMIN_DELETED"
    TRANSACTION_VERIFIED = "TRANSACTION_VERIFIED"
    AGENT_MARKED_PAID = "AGENT_MARKED_PAID"


class PropertyCategory(StrEnum):
    LAND = "LAND"
    HOUSE = "HOUSE"
    APARTMENT = "APARTMENT"
    COMMERCIAL = "COMMERCIAL"
    OFFICE = "OFFICE"
    SHOP = "SHOP"
    WAREHOUSE = "WAREHOUSE"


class ListingType(StrEnum):
    SALE = "SALE"
    RENT = "RENT"
    SHORTLET = "SHORTLET"


class PropertyStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    SOLD = "SOLD"
    RENTED = "RENTED"
    PENDING = "PENDING"
    HIDDEN = "HIDDEN"


class PropertySort(StrEnum):
    NEWEST = "newest"
    OLDEST = "oldest"
    PRICE_ASC = "price_asc"
    PRICE_DESC = "price_desc"


class MediaType(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    DOCUMENT = "DOCUMENT"


class TokenType(StrEnum):
    ACCESS = "access"
    REFRESH = "refresh"


class Environment(StrEnum):
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class TransactionProvider(StrEnum):
    PAYSTACK = "PAYSTACK"


class TransactionType(StrEnum):
    AGENT_SUBSCRIPTION = "AGENT_SUBSCRIPTION"
    AGENT_VERIFICATION = "AGENT_VERIFICATION"  # Legacy compatibility.


class TransactionStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"
    ONGOING = "ONGOING"
    CANCELLED = "CANCELLED"


class ChatType(StrEnum):
    PRIVATE = "PRIVATE"
    GROUP = "GROUP"


class ChatParticipantRole(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MEMBER = "MEMBER"


class MessageType(StrEnum):
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    SYSTEM = "SYSTEM"
